set_version("0.95")
set_languages("gnu99", "cxx17")
add_requires("libsdl2", "libsdl2_image", "libsdl2_gfx", "libsdl2_mixer > 2.6.2", "libsdl2_ttf", "libintl", "lua > 5.4.6", "cereal", "soloud", "spdlog")

target("yeoldedink")
    set_kind("binary")
    add_cxxflags("-Wno-write-strings")
    add_files("src/*.cpp")
    add_files("src/*.c")
    add_files("soloud/*.cpp")
    add_files("src/imgui_standard/*.cpp")
    add_files("src/imgui_standard/misc/freetype/*.cpp")

    add_cxflags("-DHAVE_CONFIG_H", "-DWELL_BEHAVED_DINK")
    set_configvar("PACKAGE", "yeoldedink")
    set_configvar("PACKAGE_NAME", "$(target)")
    set_configvar("PACKAGE_STRING", "yeoldedink $(version)")
    set_configvar("PACKAGE_BUGREPORT", "billy@cock.li")
    set_configvar("BUILD_DATA_DIR", "share")
    set_configvar("LOCALEDIR", "locale")
    add_configfiles("include/config.h.in")

    add_includedirs("include", "soloud", "src/imgui_standard/misc/freetype", "$(buildir)")
    add_packages("libsdl2", "libsdl2_image", "libsdl2_mixer", "libsdl2_gfx", "libsdl2_ttf", "libintl", "lua", "cereal", "soloud", "spdlog")
